import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Katla Bugis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto text-center flex flex-col justify-center items-center h-screen">
        <h1 className="text-5xl font-bold">KATLA </h1>
        <p className="text-xl">(Versi Bahasa Bugis)</p>

        <p className="mt-5 text-2xl font-bold">Coming Soon!</p>
      </main>
    </div>
  )
}
