import Head from "next/head"
import Wordle from "../components/Wordle"

export async function getServerSideProps(context) {
  const res = await fetch("https://katla-bugis-api.vercel.app/solutions.json")
  const data = await res.json()
  console.log(data)
  const solutions = data.data

  const solution = solutions[Math.floor(Math.random() * solutions.length)].word

  return { props: { solution } }
}

function Home({ solution }) {
  console.log(solution)

  return (
    <div>
      <Head>
        <title>Katla Bugis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto text-center flex flex-col items-center h-screen">
        <div className="py-2">
          <h1 className="text-3xl font-bold">KATLA </h1>
          <p>Bahasa Bugis</p>
          {/* {solution} */}
        </div>

        {solution && <Wordle solution={solution} />}
      </main>
    </div>
  )
}

export default Home
